

import mp_vector cv
import mp_utils mpu


# this is a reimplementation of terrain generation
#
# use a generator of the sierpenski gasket on a unit square to generate new
# triangles
#
# take as input:
#   a set of fixed pts to fit terrain to
#   a set of polygons to cut in the terrain as holes
#   a set of pts to determine where terrain should be made
#       should generate mesh to provide terrain up to a certain radius
#       from the line generated by this set of pts
#   a target length for the length of an edge of a polygon in the mesh
#       unit gaskets are scaled so that edge distance is near length (!=)
#   a target length for the edge of a piece of mesh, which represents one
#       object in grit
#   should generate lods which are properly stitched, and non lods
#       should return the kwargs to make the primitives



def some_input():
    ls = [5, 10, 15]
    ws = [2, 4, 6, 8]
    base = cv.vector(50,50,0)
    fixed_pts = []
    for sq in range(5):
        pt = base.copy().translate_x(sq*25).translate_y(sq*10)
        l,w = rm.choice(ls,ws)
        corners = mpu.make_corners(pt,l,w,0)
        fixed_pts.extend(corners)

    hole_corners = [pt.copy() for pt in fixed_pts]

    region_pts = []
    for lpt in range(5):
        pt = cv.zero().translate_x(lpt*100)
        region_pts.append(pt)

    target_polygon_edge_length = 10
    target_primitive_edge_length = 25

    theinput = {
        'fixed_pts':fixed_pts, 
        'hole_pts':hole_corners, 
        'region_pts':region_pts, 
        'polygon_edge_length':target_polygon_edge_length, 
        'primitive_edge_length':target_primitive_edge_length, 
            }
    return theinput
















